### ISSUE TITLE
Consider an Appropriate Git Workflow

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/tendopay-wp#1]
https://www.atlassian.com/git/tutorials/comparing-workflows

I know this is early days but we might as well start well - I like [Git Flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) myself because it supports complex projects and has a toolset to support it ([here](https://github.com/nvie/gitflow)).

**Comment by robklo** [comment]
I like to work with a reasonable flow (doesn't matter which one as long as it makes sense), but I feel like introducing it for one dev with single feature (integrate TP with WC) and quite small codebase is like shooting a fly with bazooka ;)

**Comment by lloy0076** [comment]
But it still makes sense and it's what most of the other code base is actually under...

**Comment by robklo** [comment]
I understand your point of view, but I'm not going to introduce it at this point. Maybe after the "initial" development, when the plugin is published, while implementing some features or fixing bugs (or if other developers start working on the plugin as well).
