### ISSUE TITLE
Plugin License

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/tendopay-wp#3]
@pmkay Double check if the GPLv3 or later is OK - both with TP's needs and WP's.

**Comment by robklo** [comment]
@pmkay @lloy0076 for plugins in WP plugins repository (https://wordpress.org/plugins/) the license must be compatible with GPLv2 or later. See: https://wordpress.org/plugins/developers/

**Comment by lloy0076** [comment]
Aye, this is more to get the OK from @archivum BEFORE the thing gets released and goes out of their control.
