### ISSUE TITLE
Cloning and Waking (Singletons)

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/tendopay-wp#5]
https://github.com/TendoPayPlugins/tendopay-wp/blob/18f4639f636dc86fd74b6f617e46506c0e53b849/tendopay.php#L19

- https://www.phptherightway.com/pages/Design-Patterns.html

To get this "perfect" we should disable clone and wake too.

**Comment by robklo** [comment]
It's not a singleton, actually, but it should definitely be. Will change it.
