### ISSUE TITLE
customer_reference_3

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/tendopay-wp#6]
https://github.com/TendoPayPlugins/tendopay-wp/blob/18f4639f636dc86fd74b6f617e46506c0e53b849/src/Tendopay/API/Authorization_Endpoint.php#L37

...there's a third one isn't there?

**Comment by robklo** [comment]
Only first two are used by the plugin - for order_id and order_key. Third is optional and I had no need for using it. Did I misunderstood its meaning?

**Comment by lloy0076** [comment]
I wonder if some customers might want something in there that's completely customisable to them?

**Comment by robklo** [comment]
This is why do_action/apply_filters was introduced. It will add functionality to customize the plugin. It will be added at the end of the development. 

I think Dillbert didn't say anything like that, did he? 🙈

**Comment by pmkay** [comment]
@robklo is this added?

**Comment by robklo** [comment]
@pmkay but let me double check it
