### ISSUE TITLE
Contributor (Owner)

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/tendopay-wp#7]
https://github.com/TendoPayPlugins/tendopay-wp/blob/18f4639f636dc86fd74b6f617e46506c0e53b849/readme.txt#L2

Who owns this code:

- TP (in which case **they** own the copyright and are the contributor despite robert being the coder)?
- robert?

**Comment by robklo** [comment]
The readme.txt file is mostly for setting up the plugin page, e.g.: https://wordpress.org/plugins/voucherify.

The purpose of contributors "tag" is to show who actually developed the plugin (has little to no relation to owning copyright, it's only about the authorship), and it has to be a handle that will show up on the plugin's page in the "developers" section e.g.: https://wordpress.org/plugins/voucherify/#developers-header

We could add a handle to the wp account I've got from @archivum and @pmkay
