### ISSUE TITLE
Versions are Not Constants

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/tendopay-wp#8]
https://github.com/TendoPayPlugins/tendopay-wp/blob/75a7da3c7fd7a6279313c7fd8f3a9021c46f9460/src/TendoPay/Woocommerce_Order_Description_Retriever.php#L122

That seems odd given the rest of the code 😄.

**Comment by robklo** [comment]
why?

**Comment by pmkay** [comment]
I'm closing this cause I see no issue with this
