### ISSUE TITLE
Is Valid Response

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/tendopay-wp#9]
https://github.com/TendoPayPlugins/tendopay-wp/blob/75a7da3c7fd7a6279313c7fd8f3a9021c46f9460/src/TendoPay/API/Authorization_Endpoint.php#L48

That seems odd to me; if it's empty, it's OK?

**Comment by robklo** [comment]
I have no idea how I could come up with all of this 😕 🤣 

`$is_valid_response` should contain true if all went OK and the exception should be thrown if `$is_valid_response` is `false`

Will fix that!
